apiVersion: v1
kind: Config
current-context: minikube
clusters:
- name: minikube
  cluster:
    insecure-skip-tls-verify: true
    server: https://host.docker.internal:54011
contexts:
- name: minikube
  context:
    cluster: minikube
    user: minikube
    namespace: prod-tf
users:
- name: minikube
  user:
    client-certificate: /var/jenkins_home/.minikube/profiles/minikube/client.crt
    client-key: /var/jenkins_home/.minikube/profiles/minikube/client.key